version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my_fastapi_app
    command: "uvicorn main:app --host 0.0.0.0 --port 8000"
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    depends_on:
      - mongodb
    environment:
      MONGO_DETAILS: mongodb://mongodb:27017
  mongodb:
    image: mongo:latest
    container_name: my_mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
